import { DataProducto } from "./types/interface";
interface ProductosPorCategoria {
  [categoria: string]: DataProducto[];
}

const productos: ProductosPorCategoria = {
  "Entradas-y-picoteos": [
    {
      nombre: "Ceviche Tradicional",
      precioNormal: "4990",
      precioOferta: null,
      descripcion: [
        "Pescado blanca, leche de tigre tradicional, cebolla morada",
        "cilantro, canchas de maíz y camote dulce.",
      ],
      disponible: true,
    },
    {
      nombre: "Ebi Tempura",
      precioNormal: "4990",
      precioOferta: null,
      descripcion: ["5 camarones apanados"],
      disponible: true,
    },
    {
      nombre: "Antojito Japones",
      precioNormal: "5990",
      precioOferta: null,
      descripcion: [
        "5 Camarón tempura, queso crema, envuelto en",
        "platano con toping de salsa dinamita.",
      ],
      disponible: true,
    },
    {
      nombre: "Kany Crunchy",
      precioNormal: "4990",
      precioOferta: null,
      descripcion: ["Kany crujiente en salsa del chef."],
      disponible: true,
    },
    {
      nombre: "Camarones filadelfia",
      precioNormal: "5990",
      precioOferta: null,
      descripcion: [
        "5 Camarones apanados envueltos en queso",
        "filadelfia y en panko",
      ],
      disponible: true,
    },
  ],
  Promociones: [
    {
      nombre: "20 piezas",
      subCategoria: "Fríos",
      precioNormal: "9990",
      precioOferta: null,
      descripcion: [
        "10 Camaron",
        "Queso crema, Cebollin,",
        "Envueltos en palta.",
        "10 Pollo",
        "Queso crema, Cebollin,",
        "Tempura.",
      ],
      disponible: true,
    },
    {
      nombre: "30 piezas",
      subCategoria: "Fríos",
      precioNormal: "13990",
      precioOferta: null,
      descripcion: [
        "10 Camaron",
        "Queso crema, Cebollin,",
        "Envueltos en palta.",
        "10 Kanikama",
        "Palta, cebollin envuelto",
        "en sesamo.",
        "10 Pollo",
        "Queso crema, Cebollin,",
        "Tempura.",
      ],
      disponible: true,
    },
    {
      nombre: "40 piezas",
      subCategoria: "Fríos",
      precioNormal: "16990",
      precioOferta: null,
      descripcion: [
        "10 Camaron",
        "Queso crema, Cebollin,",
        "Envueltos en palta.",
        "10 Palmito",
        "Palta, cebollin envuelto",
        "en sesamo.",
        "10 Kanikama",
        "Palta, cebollin envuelto",
        "en sesamo.",
        "10 Pollo",
        "Queso crema, Cebollin,",
        "Tempura.",
      ],
      disponible: true,
    },
    {
      nombre: "50 piezas",
      subCategoria: "Fríos",
      precioNormal: "19990",
      precioOferta: null,
      descripcion: [
        "10 Camaron",
        "Queso crema, Cebollin,",
        "Envueltos en palta.",
        "10 Salmon",
        "Palta, cebollin envuelto",
        "en sesamo.",
        "10 Pollo",
        "Queso crema, Cebollin,",
        "Tempurado con topping de kanikama.",
        "10 Kanikama",
        "Queso crema, cebollin, envuelto",
        "en ciboulette con salsa acevichada",
        "10 Palmito",
        "Queso crema, cebollin envuelto",
        "tempurizado.",
      ],
      disponible: true,
    },
    {
      nombre: "60 piezas",
      subCategoria: "Fríos",
      precioNormal: "22990",
      precioOferta: null,
      descripcion: [
        "10 Camaron",
        "Queso crema, Cebollin,",
        "Envueltos en palta.",
        "10 Salmon",
        "Palta, cebollin envuelto",
        "en sesamo.",
        "10 Pollo teriyaki",
        "Queso crema, Cebollin,",
        "En Panko con topping de kanikama.",
        "10 Kanikama",
        "Queso crema, cebollin, envuelto",
        "en ciboulette con salsa acevichada",
        "10 Palmito",
        "Queso crema, cebollin envuelto",
        "tempurizado.",
        "10 Pollo",
        "Queso crema, cebollin, envuelto",
        "En platano o queso crema",
      ],
      disponible: true,
    },
    {
      nombre: "30 piezas",
      subCategoria: "Tempura",
      precioNormal: "11990",
      precioOferta: null,
      descripcion: [
        "10 Pollo apanado",
        "Queso crema, Cebollin en panko",
        "10 Camaron",
        "Queso crema, Cebollin en panko",
        "10 Palmito",
        "Queso crema, Cebollin en panko",
      ],
      disponible: true,
    },
    {
      nombre: "40 piezas",
      subCategoria: "Tempura",
      precioNormal: "14990",
      precioOferta: null,
      descripcion: [
        "10 Pollo apanado",
        "Queso crema, Cebollin en panko",
        "10 Kanikama",
        "Queso crema, Cebollin en panko",
        "10 Camaron",
        "Queso crema, Cebollin en panko",
        "10 Palmito",
        "Queso crema, Cebollin en panko",
      ],
      disponible: true,
    },
  ],
  "Sakura-rolls-especiales": [
    {
      nombre: "Saku especial roll (Uramaki)",
      precioNormal: "8990",
      precioOferta: null,
      descripcion: [
        "Relleno de Camarón Apanado, Queso Crema y Palta",
        "Envoltura de Ciboulette",
        "Topping de Tartaro Nikkei de atún",
        "Bañado en Salsa de Masago",
      ],
      url_image: "images/sushi_frio_saku_especial_roll.png",
      disponible: true,
    },
    {
      nombre: "Dinamita roll (Uramaki)",
      precioNormal: "8990",
      precioOferta: null,
      descripcion: [
        "Relleno de Camarón Apanado, Queso Crema y Ciboulette",
        "Envoltura mitad Palta mitad Salmón",
        "Topping de Kanikama especial",
        "Bañado en salsa de masago",
        "Coronado con sesamo",
      ],
      url_image: "images/sushi_frio_dinamita_roll.png",
      disponible: true,
    },
    {
      nombre: "Yaki roll (Tempura)",
      precioNormal: "8490",
      precioOferta: null,
      descripcion: [
        "Relleno de Kanikama, Queso Crema y Ciboulette",
        "Topping de Wakame",
        "Bañado en Salsa de Masago y Salsa Teriyaki",
        "Coronado con Kanikama Crunsh",
      ],
      url_image: "images/sushi_tempura_yaki_roll.png",
      disponible: true,
    },
    {
      nombre: "Acevichado roll (Uramaki)",
      precioNormal: "8990",
      precioOferta: null,
      descripcion: [
        "Relleno de Camarón Apanado, queso crema y Kanikama",
        "Envoltura de Palta",
        "Topping de ceviche",
        "Bañado en Salsa Acevichada",
        "Coronado con Togarashi y cancha",
      ],
      url_image: "images/sushi_frio_acevichado_roll.png",
      disponible: true,
    },
    {
      nombre: "Spicy roll (Uramaki)",
      precioNormal: "8990",
      precioOferta: null,
      descripcion: [
        "Relleno de Salmón, Queso Crema y Palta",
        "Envuelto en Sesamo",
        "Topping de Kanikama especial",
        "Bañado en Salsa de Rocoto",
        "Coronado con Togarashi",
      ],
      url_image: "images/sushi_frio_spicy_roll.png",
      disponible: true,
    },
    {
      nombre: "Platano roll (Uramaki)",
      precioNormal: "8990",
      precioOferta: null,
      descripcion: [
        "Relleno de Camarón Apanado, Queso Crema y Cebollín",
        "Envuelto en Plátano",
        "Topping de Kanikama especial",
        "Bañado en Salsa Teriyaki",
        "Coronado con ciboulette.",
      ],
      url_image: "images/sushi_frio_platano_roll.png",
      disponible: true,
    },
    {
      nombre: "Tokio roll (Futomaki apanado)",
      precioNormal: "7990",
      precioOferta: null,
      descripcion: [
        "Relleno de Kanikama apanado, Camarón Apanado, Queso Crema, Cebollín",
        "Topping de ensalada neptuno",
        "Bañado con Salsa Teriyaki",
        "Coronado con masago",
      ],
      url_image: "images/sushi_tempura_tokio_roll.png",
      disponible: true,
    },
    {
      nombre: "Tropical roll (Uramaki)",
      precioNormal: "8490",
      precioOferta: null,
      descripcion: [
        "Relleno de Camarón Apanado, Kanikama, Queso Crema",
        "Envoltura de Palta",
        "Topping de Chalaca (cebolla morada, ciboulette, rocoto, ají amarillo y cilantro)",
        "Coronado con Kanikama Crunsh",
        "Salsa de Leche de Tigre de Maracuyá en la base del plato",
      ],
      url_image: "images/sushi_frio_tropical_roll.png",
      disponible: true,
    },
    {
      nombre: "Fugi roll (Uramaki)",
      precioNormal: "7990",
      precioOferta: null,
      descripcion: [
        "Relleno de Kanikama apanado, Palta, Queso Crema",
        "Envuelto en Sesamo",
        "Topping de Camarón Apanado",
        "Bañado en Salsa Fugi",
        "Coronado con ciboulette.",
      ],
      url_image: "images/sushi_frio_fugi_roll.png",
      disponible: true,
    },
    {
      nombre: "Dako roll (Sin arroz)",
      precioNormal: "9990",
      precioOferta: null,
      descripcion: [
        "Relleno de Salmón, Camarón Apanado, Kanikama apanado, Queso Crema palta y ciboulette",
        "Topping de Kanikama especial",
        "Bañado en salsa de masago y Salsa Angila",
        "Coronado con sesamo",
      ],
      url_image: "images/sushi_tempura_dako_roll.png",
      disponible: true,
    },
    {
      nombre: "Super Ligth roll (Sin arroz)",
      precioNormal: "10990",
      precioOferta: null,
      descripcion: [
        "Relleno de Salmón, Camarón Apanado, Kanikama apanado, Queso Crema, Palta y Ciboulette",
        "Envoltura de Salmón",
        "Salsa acevichada",
        "Coronado con masago.",
      ],
      url_image: "images/sushi_frio_super_ligth_roll.png",
      disponible: true,
    },
  ],
  SushiBurger: [
    {
      nombre: "Hamburguesa Sake",
      precioNormal: "9990",
      precioOferta: null,
      descripcion: [
        "Salmón, queso crema, cebollín, palta, en panko con",
        "nuestras salsas especiales.",
      ],
      disponible: true,
    },
    {
      nombre: "Hamburguesa Ebi",
      precioNormal: "9990",
      precioOferta: null,
      descripcion: [
        "Camarón apanado, queso crema, cebollín, palta en",
        "panko con nuestras salsas especiales",
      ],
      disponible: true,
    },
    {
      nombre: "Hamburguesa Mixta",
      precioNormal: "11990",
      precioOferta: null,
      descripcion: [
        "Salmón, camarón apanado, queso crema cebollín,",
        "palta, en panko, con nuestras salsa especiales.",
      ],
      disponible: true,
    },
    {
      nombre: "Hamburguesa Tori",
      precioNormal: "8490",
      precioOferta: null,
      descripcion: [
        "Pollo, queso crema, cebollín, palta, en panko, con",
        "nuestras salsas especiales.",
      ],
      disponible: true,
    },
    {
      nombre: "Hamburguesa Kani",
      precioNormal: "6990",
      precioOferta: null,
      descripcion: [
        "Kanikama, queso crema, cebollín, palta, en panko, con",
        "nuestras salsas especiales.",
      ],
      disponible: true,
    },
    {
      nombre: "Hamburguesa Vegetariana",
      precioNormal: "6990",
      precioOferta: null,
      descripcion: [
        "Vegetales, queso crema, cebollín, palta, en panko, con",
        "nuestras salsas especiales.",
      ],
      disponible: true,
    },
    {
      nombre: "Hamburguesa Vegana",
      precioNormal: "6990",
      precioOferta: null,
      descripcion: [
        "Vegetales, cebollín, palta, panko, con nuestras salsas",
        "especiales.",
      ],
      disponible: true,
    },
  ],
  Handrolls: [
    {
      nombre: "Hand rolls Vegetariano",
      precioNormal: "3490",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
    {
      nombre: "Hand rolls Pollo",
      precioNormal: "3490",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
    {
      nombre: "Hand rolls Camaron",
      precioNormal: "3990",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
    {
      nombre: "Hand rolls Salmon",
      precioNormal: "3990",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
  ],
  Gohan: [
    {
      nombre: "Gohan de Salmon",
      precioNormal: "7990",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
    {
      nombre: "Gohan de Camaron",
      precioNormal: "6490",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
    {
      nombre: "Gohan de Pollo",
      precioNormal: "5990",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
    {
      nombre: "Gohan Acevichado",
      precioNormal: "8990",
      precioOferta: null,
      descripcion: null,
      disponible: true,
    },
  ],
};

export default productos;
